export const STORE_STATUS = {
  /** Generic States */
  NOT_STARTED: 'NOT_STARTED',
  LOADING: 'LOADING',
  /** ProductListing States */
  LOAD_PRODUCTS_SUCCESS: 'LOAD_PRODUCTS_SUCCESS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  /** ProductDetail States */
  LOAD_DETAIL_SUCCESS: 'LOAD_DETAIL_SUCCESS',
  LOAD_DETAIL_ERROR: 'LOAD_DETAIL_ERROR'
}
