export const LOAD_CATALOG_ACTION = 'LOAD_CATALOG_ACTION'
export const LOAD_CATALOG_ACTION_COMPLETED = 'LOAD_CATALOG_ACTION_COMPLETED'
export const LOAD_CATALOG_ACTION_FAILED = 'LOAD_CATALOG_ACTION_FAILED'

export const LOAD_DETAIL_ACTION = 'LOAD_DETAIL_ACTION'
export const LOAD_DETAIL_ACTION_COMPLETED = 'LOAD_DETAIL_ACTION_COMPLETED'
export const LOAD_DETAIL_ACTION_FAILED = 'LOAD_DETAIL_ACTION_FAILED'

export const LOAD_OFFERING_ACTION = 'LOAD_OFFERING_ACTION'
export const LOAD_OFFERING_ACTION_COMPLETED = 'LOAD_OFFERING_ACTION_COMPLETED'
export const LOAD_OFFERING_ACTION_FAILED = 'LOAD_OFFERING_ACTION_FAILED'
